# Generated by Django 5.2.14 on 2026-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('subject_teacher_name', models.CharField(max_length=10)),
            ],
        ),
    ]
