# Generated by Django 5.2.14 on 2026-06-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Python', max_length=100),
            preserve_default=False,
        ),
    ]
