# Generated by Django 5.2.14 on 2026-06-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0004_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frameworks.student'),
            preserve_default=False,
        ),
    ]
